### ISSUE TITLE
Unable to access data offline - Node CLI

### ISSUE THREAD

**Issue by arjunpola** [mongodb-university/realm-tutorial#67]
Firstly, I thank the author for providing this tutorial on how to setup MongoDB Realm using Node-CLI.

My concern is on accessing the data in offline mode. I was unable to access data on performing:
1) Successfully authenticate
2) Add few tasks and make sure they are added in web console
3) Also make sure they are displayed in the terminal (By selecting Option 2 i.e "Show all of my tasks")
4) Logout and close the node application
5) Re-run the node application and authenticate with the same user
6) Disconnect network connection and try to view the data (By selecting Option 2 i.e "Show all of my tasks").

Please advice on how to address this issue.

Tested on
OS: macOS Catalina (ver 10.15.6)
Node Version: v12.18.1
NPM Version: 6.14.5

**Comment by ianpward** [comment]
@arjunpola  Can you share the logs on the client side and the logs from your server please?

**Comment by MongoCaleb** [comment]
@arjunpola - thanks for reporting this. It was a bug in the tutorial code, which is addressed in https://github.com/mongodb-university/realm-tutorial/pull/68. Should be merged in soon!

**Comment by arjunpola** [comment]
@MongoCaleb on trying the fix in #68, the offline data access issue seems to be resolved partially. Verified the working of tasks being synced when created in offline more and being able to retrieve tasks after disconnecting the network. But, the first call to **Show all of my tasks** when in offline-mode still fails.

Consider the following scenario.

1) Login (with an existing or as new user)
2) Create few tasks
3) Quit the node-cli script without logging out.
4) Turn off internet connection
5) Run the script 
6) Select **Option 1: Log In** and verify that it is automatically logged in.
7) Select **Option 2: Show all of my tasks** to see the network error.

The above issue occurs when tried with the latest beta version i.e **realm@^10.0.0-beta.13**. 

Is this an expected behaviour or something that needs to be addressed?

**Comment by arjunpola** [comment]
@MongoCaleb looking for your review on the above question. Please suggest me if I have to close this issue?
